from collections import namedtuple

Rom = namedtuple(
    "Rom",
    [
        "id",
        "platform_id",
        "platform_slug",
        "fs_name",
        "fs_name_no_tags",
        "fs_name_no_ext",
        "fs_extension",
        "fs_size",
        "fs_size_bytes",
        "name",
        "slug",
        "summary",
        "youtube_video_id",
        "path_cover_small",
        "path_cover_large",
        "is_identified",
        "revision",
        "regions",
        "languages",
        "tags",
        "crc_hash",
        "md5_hash",
        "sha1_hash",
        "has_simple_single_file",
        "has_nested_single_file",
        "has_multiple_files",
        "merged_screenshots",
        "genres",
        "franchises",
        "collections",
        "companies",
        "game_modes",
        "age_ratings",
        "first_release_date",
        "average_rating",
    ],
)
Collection = namedtuple("Collection", ["id", "name", "rom_count", "virtual"])
Platform = namedtuple("Platform", ["id", "display_name", "slug", "rom_count"])
